export const colorMap: Record<string, string> = {
  darkBackground: 'rgba(18, 18, 18, 1)',
  darkWidget: 'rgba(30, 30, 30, 1)',
  darkWidget2: 'rgba(40, 40, 40, 1)',
  darkWidget3: 'rgba(48, 48, 48, 1)',
  darkText: 'rgb(235, 235, 235)',
  darkText2: 'rgba(158, 158, 158, 1)',
  darkText3: 'rgb(217, 209, 209)',
  darkShadow: 'rgba(0, 0, 0, 1)',
  darkGrid: 'rgb(55, 55, 55)',
  lightBackground: 'rgba(247, 247, 247, 1)',
  lightWidget: 'rgba(255, 255, 255, 1)',
  lightWidget2: 'rgba(229, 229, 229, 1)',
  lightWidget3: 'rgb(240, 240, 240)',
  lightText: 'rgba(33, 36, 39, 1)',
  lightText2: 'rgba(120, 120, 120, 1)',
  lightText3: 'rgb(23, 23, 23)',
  lightShadow: 'rgba(199, 199, 199, 1)',
  lightGrid: 'rgb(200, 200, 200)',
  green: 'rgba(81, 158, 25, 1)',
};


export const intensityColor: Record<string, string> = {
  "Not in season": "#6F6F6F",
  "Very low": '#37740A',
  "Low": '#55A01E',
  "Moderate": '#E9C716',
  "High": '#DB7E0D',
  "Very high": '#DF1C28',
};

export const intensityColor2: Record<string, string> = {
  "Not selected": "rgb(68, 68, 68)",
  "Not in season": "#6F6F6F",
  "Very low": '#274E0A',
  "Low": '#3F890A',
  "Moderate": '#DFB009',
  "High": '#D87803',
  "Very high": '#B60C17',
};

export const intensityColor3: Record<number, string> = {
  [-1]: "rgb(68, 68, 68)",
  0: "#6F6F6F",
  1: '#274E0A',
  2: '#3F890A',
  3: '#DFB009',
  4: '#D87803',
  5: '#B60C17',
};

export const defaultBloomingDates: Record<string, string[]> = {
  "ragweed": ["25/7", "10/10"],
  "mugwort": ["20/7", "30/9"],
  "birch": ["10/4", "10/5"],
  "poplar": ["20/3", "30/4"],
  "nettle": ["1/6", "25/7"],
  "goosefoot": ["20/6", "30/9"],
  "timothy": ["25/5", "10/7"]
};

export const months: Record<number, string> = {
  1: "January",
  2: "February",
  3: "March",
  4: "April",
  5: "May",
  6: "June",
  7: "July",
  8: "August",
  9: "September",
  10: "October",
  11: "November",
  12: "December",
};

export const weekdays: Record<number, string> = {
  0: "Sunday",
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday",
};

export const bloomingNow: Array<[string, string, string, string]> = [
  ["Ragweed", "High", "10/14", "10/26"],
  ["Mugwort", "Very low", "8/3", "8/15"]
];

export const upcoming: Array<[string, string]> = [
  ["Birch", "17 Квітня"],
  ["Timothy", "25 Червня"],
  ["Poplar", "12 Квітня"],
];

export const bloomingDict: Record<string, [string, string, string, string]> = {
  "Ragweed": ["Ragweed", "High", "10/14", "10/26"],
  "Mugwort": ["Mugwort", "Very low", "8/3", "8/15"],
};

export const upcomingDict: Record<string, [string, string, string]> = {
  "Birch": ["Birch", "17 Квітня", "4/19"],
  "Timothy": ["Timothy", "25 Червня", "6/8"],
  "Poplar": ["Poplar", "12 Квітня", "6/8"],
};

export const translation: Record<string, Record<string, string>> = {
  ua: {
    "Currently blooming":"Зараз цвіте",
    "Features" : "Можливості",
    "Upcoming" : "Скоро",
    "Allergy progression": "Статус алергії",
    "Your location": "Ваша локація",
    "Monday": "Понеділок",
    "Tuesday": "Вівторок",
    "Wednesday": "Середа",
    "Thursday": "Четвер",
    "Friday": "П'ятниця",
    "Saturday": "Субота",
    "Sunday": "Неділя",
    "January": "Січень",
    "February": "Лютий",
    "March": "Березень",
    "April": "Квітень",
    "May": "Травень",
    "June": "Червень",
    "July": "Липень",
    "August": "Серпень",
    "September": "Вересень",
    "October": "Жовтень",
    "November": "Листопад",
    "December": "Грудня",
    "Mugwort": "Полин",
    "Ragweed": "Амброзія",
    "Birch": "Береза",
    "Alder": "Вільха",
    "Timothy": "Тимофіївка",
    "mugwort": "Полин",
    "ragweed": "Амброзія",
    "birch": "Береза",
    "alder": "Вільха",
    "timothy": "Тимофіївка",
    "Poplar": "Тополя",
    "Nettle": "Кропива",
    "Goosefoot": "Лобода",
    "poplar": "Тополя",
    "nettle": "Кропива",
    "goosefoot": "Лобода",
    "Start": "початок",
    "End": "кінець",
    "Select Plant": "Оберіть рослину",
    "Settings": "Налаштування",
    "Done": "Готово",
    "Edit": "Змінити",
    "Account": "Аккаунт",
    "Language": "Мова",
    "Location": "Локація",
    "🇺🇦 Ukrainian": "🇺🇦 Українська",
    "🇬🇧 English": "🇬🇧 Англійська",
    "Kyiv": "Київ",
    "Tree": "Дерева",
    "Grass": "Трави",
    "Weed": "Бур'яни",
    "Search Location": "Шукати локацію",
    "Theme": "Тема",
    "Dark": "Темна",
    "Very low": "Дуже низький",
    "Low": "Низький",
    "Moderate": "Помірний",
    "High": "Високий",
    "Very high": "Дуже високий",
    "Not in season": "Не в сезоні",
    "Allergenic Plants": "Алергенні рослини",
    "Plants": "Рослини",
    "Plants library": "Бібліотека рослин",
    "Back": "Назад",
    "The plants you have selected are currently out of season": "Обрані вами рослини наразі не в сезоні",
    "Ash": "Ясен",
    "Cotton wood": "Бавовняне дерево",
    "Elm": "В'яз",
    "Maple": "Клен",
    "Olive": "Оливкове деревр",
    "Juniper": "Ялівець",
    "Oak": "Дуб",
    "Pine": "Сосна",
    "Cypress pine": "Кипарисова сосна",
    "Hazel": "Ліщина",
    "Graminales": "Злакові трави",
    "Grasses": "Злакові трави",
    "Very Low": "Дуже низький",
    "Very High": "Дуже високий",
    "Data unavailable": "Дані недоступні",
    "Pollen is not detected": "Пилок не знайдено",
    "Banana": "Банан",
    "Melon": "Диня",
    "Watermelon": "Кавун",
    "Zucchini": "Кабачок",
    "Cucumber": "Огірок",
    "Sunflower seeds": "Насіння соняшника",
    "Celery": "Селера",
    "Carrot": "Морква",
    "Mango": "Манго",
    "Peach": "Персик",
    "Mustard": "Гірчиця",
    "Apple": "Яблуко",
    "Pear": "Груша",
    "Cherry": "Вишня",
    "Plum": "Слива",
    "Kiwi": "Ківі",
    "Hazelnut": "Фундук",
    "Willow": "Верба",
    "Cottonwood": "Тополя",
    "Aspen": "Осика",
    "Tomato": "Помідор",
    "Eggplant": "Баклажан",
    "Spinach": "Шпинат",
    "Beetroot": "Буряк",
    "Quinoa": "Кіноа",
    "Chard": "Мангольд",
    "Wheat": "Пшениця",
    "Rye": "Жито",
    "Oat": "Овес",
    "Corn": "Кукурудза",
    "Strawberry": "Полуниця",
    "Almond": "Мигдаль",
    "Cross reactions": "Перехресні реакції",
    "Cross reactivity": "Перехресні реакції",
    "Jul": "Лип",
    "Aug": "Сер",
    "Sep": "Вер",
    "Oct": "Жов",
    "Nov": "Лис",
    "Allergy season graph": "Графік сезону алергії",
    "Weekly intensity graph": "Тижневий графік рівня алергії",
    "Mon": "Пн",
    "Tue": "Вт",
    "Wed": "Ср",
    "Thu": "Чт",
    "Fri": "Пт",
    "Sat": "Сб",
    "Sun": "Нд",
    "Dec": "Грд",
    "Jan": "Січ",
    "Feb": "Лют",
    "Mar": "Бер",
    "Apr": "Квт",
    "Ma": "Трв",
    "Jun": "Чер",
    "All": "Всі",
    "Loading Allergy Data...": "Завантаження Даних...",
    "Recommendations": "Рекомендації",
    "Symptoms": "Можливі симптоми",
    "Precautions": "Запобіжні заходи",
    "Recommendation": "Рекомендації"
  },
  en: {
    "Currently blooming" : "Currently blooming",
    "Features" : "Features",
    "Upcoming" : "Upcoming",
    "Allergy progression": "Allergy progression",
    "Your location": "Your location",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "Sunday": "Sunday",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "Mugwort": "Mugwort",
    "Ragweed": "Ragweed",
    "Birch": "Birch",
    "Timothy": "Timothy",
    "Alder": "Alder",
    "mugwort": "Mugwort",
    "ragweed": "Ragweed",
    "birch": "Birch",
    "timothy": "Timothy",
    "Poplar": "Poplar",
    "Nettle": "Nettle",
    "Goosefoot": "Goosefoot",
    "poplar": "Poplar",
    "nettle": "Nettle",
    "goosefoot": "Goosefoot",
    "alder": "Alder",
    "Start": "start",
    "End": "end",
    "Select Plant": "Select Plant",
    "Settings": "Settings",
    "Done": "Done",
    "Edit": "Edit",
    "Language": "Language",
    "Location": "Location",
    "Kyiv": "Kyiv",
    "🇺🇦 Ukrainian": "🇺🇦 Ukrainian",
    "🇬🇧 English": "🇬🇧 English",
    "Tree": "Tree",
    "Grass": "Grass",
    "Weed": "Weed",
    "Search Location": "Search Location",
    "Theme": "Theme",
    "Very low": "Very low",
    "Low": "Low",
    "Moderate": "Moderate",
    "High": "High",
    "Very high": "Very high",
    "Not in season": "Not in season",
    "Allergenic Plants": "Allergenic Plants",
    "Plants": "Plants",
    "Plants library": "Plants library",
    "Back": "Back",
    "The plants you have selected are currently out of season": "The plants you have selected are currently out of season",
    "Ash": "Ash",
    "Cotton wood": "Cotton wood",
    "Elm": "Elm",
    "Maple": "Maple",
    "Olive": "Olive",
    "Juniper": "Juniper",
    "Oak": "Oak",
    "Pine": "Pine",
    "Cypress pine": "Cypress pine",
    "Hazel": "Hazel",
    "Graminales": "Graminales",
    "Grasses": "Graminales",
    "Very Low": "Very low",
    "Very High": "Very high",
    "Data unavailable": "Data unavailable",
    "Pollen not detected": "Pollen not detected",
    "Banana": "Banana",
    "Melon": "Melon",
    "Watermelon": "Watermelon",
    "Zucchini": "Zucchini",
    "Cucumber": "Cucumber",
    "Sunflower seeds": "Sunflower seeds",
    "Celery": "Celery",
    "Carrot": "Carrot",
    "Mango": "Mango",
    "Peach": "Peach",
    "Mustard": "Mustard",
    "Apple": "Apple",
    "Pear": "Pear",
    "Cherry": "Cherry",
    "Plum": "Plum",
    "Kiwi": "Kiwi",
    "Hazelnut": "Hazelnut",
    "Willow": "Willow",
    "Cottonwood": "Cottonwood",
    "Aspen": "Aspen",
    "Tomato": "Tomato",
    "Eggplant": "Eggplant",
    "Spinach": "Spinach",
    "Beetroot": "Beetroot",
    "Quinoa": "Quinoa",
    "Chard": "Chard",
    "Wheat": "Wheat",
    "Rye": "Rye",
    "Oat": "Oat",
    "Corn": "Corn",
    "Cross reactions": "Cross reactions",
    "Cross reactivity": "Cross-reactivity",
    "Jul": "Jul",
    "Aug": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Allergy season graph": "Allergy season graph",
    "Weekly intensity graph": "Weekly intensity graph",
    "Mon": "Mon",
    "Tue": "Tue",
    "Wed": "Wed",
    "Thu": "Thu",
    "Fri": "Fri",
    "Sat": "Sat",
    "Sun": "Sun",
    "Dec": "Dec",
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "Ma": "May",
    "Jun": "Jun",
    "All": "All",
    "Loading Allergy Data...": "Loading Allergy Data...",
    "Recommendations": "Recommendations",
    "Symptoms": "Symptoms",
    "Precautions": "Precautions",
    "Recommendation": "Recommendation"
  },
};

export const intensityGraphs: Record<string, Record<string, string>> = {
  ua: {
    "Very low": 'lib/assets/verylow.png',
    "Low": 'lib/assets/low.png',
    "Moderate": 'lib/assets/moderate.png',
    "High": 'lib/assets/high.png',
    "Very high": 'lib/assets/veryhigh.png',
  },
  en: {
    "Very low": 'lib/assets/verylow1.png',
    "Low": 'lib/assets/low1.png',
    "Moderate": 'lib/assets/moderate1.png',
    "High": 'lib/assets/high1.png',
    "Very high": 'lib/assets/veryhigh1.png',
  },
};
  

export const plants: Record<string, any> = {
  ragweed: {
    name: "Ragweed",
    intensity: "High",
    level: "Very high",
    image: "lib/assets/ragweed.png",
    start: "07/21/2024",
    end: "10/18/2024",
    veryLow: ["07/21/2024", "07/26/2024", "10/11/2024", "10/18/2024"],
    low: ["07/27/2024", "08/03/2024", "10/04/2024", "10/10/2024"],
    moderate: ["07/27/2024", "08/06/2024", "9/23/2024", "10/03/2024"],
    high: ["08/07/2024", "08/28/2024", "9/11/2024", "9/22/2024"],
    veryHigh: ["08/22/2024", "08/22/2024", "9/11/2024", "9/22/2024"],
  }
};

export const plantDescriptions: Record<string, Record<string, string>> = {
  "ua": {
    ragweed: "Амброзія — один із найбільш поширених алергенів, який викликає сезонну алергію наприкінці літа та на початку осені. Пилок амброзії дуже легкий і може поширюватись на відстань до 300 км.",
    mugwort: "Полин — рослина, яка виділяє алергенний пилок влітку та восени, часто викликаючи чхання, свербіж і подразнення очей.",
    birch: "Береза — дерево, що виробляє пилок навесні. Цей пилок є одним із основних тригерів сезонної алергії.",
    poplar: "Тополя — відома своїм пухом, який переносить пилок. Цвіте навесні та може викликати алергічні реакції.",
    timothy: "Тимофіївка — трава, яка виділяє алергенний пилок у середині літа. Часто впливає на людей із сінною гарячкою.",
    nettle: "Кропива — алергенний пилок цієї рослини поширений влітку. Контакт із листям може також викликати подразнення шкіри.",
    goosefoot: "Лобода — бур'ян, який виділяє пилок у другій половині літа. Один із поширених викликачів сезонної алергії.",
    alder: "Вільха — дерево, що починає пилкувати наприкінці зими та на початку весни. Її пилок є важливим тригером ранньовесняної алергії."
  },
  "en": {
    ragweed: "Ragweed is one of the most common allergens, causing seasonal allergies in late summer and early fall. Its lightweight pollen can travel up to 300 km.",
    mugwort: "Mugwort is a plant that releases allergenic pollen in summer and fall, often causing sneezing, itching, and eye irritation.",
    birch: "Birch is a tree that produces pollen in spring. Its pollen is one of the main triggers of seasonal allergies.",
    poplar: "Poplar trees are known for their fluff, which carries pollen. They bloom in spring and can cause allergic reactions.",
    timothy: "Timothy grass releases allergenic pollen in mid-summer. It often affects people with hay fever.",
    nettle: "Nettle pollen is common in summer and can cause allergies. Contact with its leaves may also irritate the skin.",
    goosefoot: "Goosefoot is a weed that releases pollen in late summer. It's a common trigger of seasonal allergies.",
    alder: "Alder is a tree that begins pollinating in late winter and early spring. Its pollen is a major trigger for early spring allergies."
  }
};


export const seasonDynamics: Record<string, Record<string, string>> = {
  "ua": {
    "ragweed": "Сезон алергії на амброзію зазвичай починається наприкінці липня або на початку серпня, досягає піку на початку чи в середині вересня та завершується до кінця жовтня.",
    "mugwort": "Сезон алергії на полин зазвичай триває з липня до кінця вересня, з піком у серпні.",
    "birch": "Сезон алергії на березу розпочинається в середині квітня, досягає піку наприкінці квітня або на початку травня і завершується в середині травня.",
    "poplar": "Сезон алергії на тополю розпочинається в середині травня та завершується до кінця червня.",
    "nettle": "Сезон алергії на кропиву триває з червня до вересня, з піком у липні та серпні.",
    "timothy": "Сезон алергії на тимофіївку починається наприкінці травня, досягає піку у червні та завершується наприкінці липня.",
    "goosefoot": "Сезон алергії на лободу триває з червня до вересня, з найбільшою інтенсивністю у серпні.",
    "alder": "Сезон алергії на вільху починається у лютому, досягає піку у березні та завершується в квітні."
  },
  "en": {
      "ragweed": "The ragweed allergy season often begins in late July or early August, peaks in early to mid-September, and ends by late October.",
      "mugwort": "The mugwort allergy season typically runs from July to late September, with a peak in August.",
      "birch": "The birch allergy season starts in mid-April, peaks in late April to early May, and ends by mid-May.",
      "poplar": "The poplar allergy season begins in mid-May and ends by late June.",
      "nettle": "The nettle allergy season lasts from June to September, peaking in July and August.",
      "timothy": "The timothy grass allergy season starts in late May, peaks in June, and ends by late July.",
      "goosefoot": "The goosefoot allergy season runs from June to September, with the highest intensity in August.",
      "alder": "The alder allergy season begins in February, peaks in March, and ends in April."
  }
};



export const crossReactions: Record<string, string[]> = {
  ragweed: ["Banana", "Melon", "Watermelon", "Zucchini", "Cucumber", "Sunflower seeds"],
  mugwort: ["Celery", "Carrot", "Mustard", "Peach", "Mango"],
  birch: ["Apple", "Pear", "Cherry", "Plum", "Kiwi", "Carrot", "Hazelnut"],
  poplar: ["Willow", "Cottonwood", "Aspen"],
  nettle: ["Tomato", "Eggplant", "Cucumber", "Melon", "Watermelon"],
  timothy: ["Wheat", "Rye", "Oat", "Corn"],
  goosefoot: ["Spinach", "Beetroot", "Quinoa", "Chard"],
  alder: ["Apple", "Cherry", "Peach", "Strawberry", "Celery", "Hazelnut", "Almond"]
};


export const bloomingDates: Record<string, string[]> = {
  ragweed: ["22/07/2025", "31/10/2025"],
  //ragweed: ["13/12/2024", "12/02/2025"],
  mugwort: ["13/07/2025", "30/09/2025"],
  //mugwort: ["01/01/2025", "20/02/2025"],
  birch: ["01/04/2025", "31/05/2025"],
  poplar: ["5/02/2025", "30/04/2025"],
  timothy: ["25/05/2025", "15/07/2025"],
  nettle: ["01/06/2025", "31/08/2025"],
  goosefoot: ["15/07/2025", "30/09/2025"],
  alder: ["15/01/2025", "27/03/2025"]
};

export const levels: Record<string, number> = { 
  ragweed: 5, 
  mugwort: 4,
  birch: 2,
  poplar: 1,
  timothy: 3,
  nettle: 1,
  goosefoot: 0,
  alder: 4
};
 

export const recommendations: Record<string, Record<string, Record<string, string>>> = {
  ua: {
    "Not in season": {
      "Message": "Насолоджуйтеся свіжим повітрям! Сьогодні пилок відсутній.",
      "Symptoms": "Відсутні",
      "Recommendations": "Не потрібні. Чудовий день для прогулянок на свіжому повітрі!",
    },
    "Very low": {
      "Message": "Рівень пилку низький. Більшість людей не відчують симптомів.",
      "Symptoms": "Можливі легке чхання або подразнення очей у дуже чутливих людей.",
      "Recommendations": "Спеціальні заходи не потрібні. Ви можете носити сонцезахисні окуляри для захисту очей. Можете спокійно гуляти на відкритому повітрі без обмежень.",
    },
    "Low": {
      "Message": "Невисокий рівень пилку. Ви можете відчувати легкі симптоми.",
      "Symptoms": "Легке чхання, нежить, періодичне подразнення очей.",
      "Recommendations": "Закрийте вікна вранці. Приймайте душ і змінюйте одяг після перебування на вулиці. Використовуйте сольовий спрей для носа. Якщо ви відчуваєте дискомфорт, використовуйте антигістамінні препарати.",
    },
    "Moderate": {
      "Message": "Помірний рівень пилку. Вам слід бути обережним!",
      "Symptoms": "Часте чхання, закладеність або нежить, свербіж і сльозотеча очей, легке утруднення дихання.",
      "Recommendations": "Обмежте перебування на вулиці, особливо вранці. Носіть сонцезахисні окуляри та головний убір. Часто мийте руки та обличчя. Приймайте антигістамінні препарати, якщо це допомагає, і використовуйте очищувач повітря.",
    },
    "High": {
      "Message": "Високий рівень пилку! Ви повинні мінімізувати вихід на вулицю.",
      "Symptoms": "Інтенсивне чхання, сильний нежить, сверблячі та набряклі очі, можливе утруднене дихання.",
      "Recommendations": "Залишайтеся вдома, тримайте вікна зачиненими, носіть маску, не сушіть одяг на вулиці. Регулярно приймайте призначені препарати та використовуйте очищувачі повітря.",
    },
    "Very high": {
      "Message": "⚠️ Екстремально високий рівень пилку! Ви повинні залишатися в приміщенні.",
      "Symptoms": "Сильна закладеність носа, утруднене дихання, можливі напади астми, ризик анафілаксії.",
      "Recommendations": "Не виходьте на вулицю без необхідності. Використовуйте очищувач повітря, мийте одяг і волосся після виходу на вулицю. Якщо у вас з’явилися важкі симптоми, негайно зверніться до лікаря.",
    },
  },
  en: {
    "Not in season": {
      "Message": "Enjoy the fresh air! No pollen detected today.",
      "Symptoms": "None",
      "Recommendations": "No special measures needed. You can safely enjoy outdoor activities!",
    },
    "Very low": {
      "Message": "Pollen levels are very low today. You are unlikely to be affected.",
      "Symptoms": "Rare cases of mild sneezing or slight eye irritation in highly sensitive individuals.",
      "Recommendations": "No special precautions needed. You can wear sunglasses to protect your eyes. You can spend time outside without any concerns.",
    },
    "Low": {
      "Message": "Pollen levels are low. You may experience mild symptoms.",
      "Symptoms": "Light sneezing, mild nasal congestion, occasional eye irritation.",
      "Recommendations": "Keep windows closed in the morning. Shower and change clothes after being outdoors. Use saline nasal spray if needed. If you feel discomfort, consider taking antihistamines.",
    },
    "Moderate": {
      "Message": "Moderate pollen levels. You should be cautious!",
      "Symptoms": "Frequent sneezing, runny or stuffy nose, itchy/watery eyes, mild breathing discomfort.",
      "Recommendations": "Limit outdoor exposure, especially in the morning. Wear sunglasses and a hat. Wash your hands and face frequently. Take antihistamines if necessary and use an air purifier indoors.",
    },
    "High": {
      "Message": "High pollen levels detected! You should minimize outdoor exposure.",
      "Symptoms": "Intense sneezing, severe nasal congestion, red, itchy, swollen eyes, difficulty breathing (possible asthma triggers).",
      "Recommendations": "Stay indoors as much as possible. Keep windows closed. Wear a high-filtration mask (e.g., N95). Avoid drying clothes outside. Follow your prescribed medications and use an air filter.",
    },
    "Very high": {
      "Message": "⚠️ Extreme pollen levels! You should stay indoors.",
      "Symptoms": "Severe congestion, difficulty breathing or asthma attacks",
      "Recommendations": "Avoid outdoor exposure unless absolutely necessary. Use an air purifier, and wash your clothes and hair after going outside. If you experience severe symptoms, seek medical attention immediately.",
    },
  },
};

